### ISSUE TITLE
تقرير الأعطال/Package Managers

### ISSUE THREAD

**Issue by jmaa4** [jmaa4/jui#1]
App Name: Package Manager
Package Name: com.smartpack.packagemanager
App Version: v7.1
SDK Version: 34

Crash Report

java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Iterator java.util.ArrayList.iterator()' on a null object reference
	at g4.h.K(SourceFile:8)
	at r3.o.b(SourceFile:14)
	at x3.a.run(SourceFile:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

Steps to reproduce the issue:

**Comment by jmaa4** [comment]
H
